export const GLOBALTYPES = {
  AUTH: "AUTH",
  ALERT: "ALERT",
  MODAL: "MODAL",
};
export const JABATAN_TYPES = {
  CREATE_JABATAN: "CREATE_JABATAN",
  LOADING_JABATAN: "LOADING_JABATAN",
  GET_JABATANS: "GET_JABATANS",
  UPDATE_JABATAN: "UPDATE_JABATAN",
  GET_JABATAN: "GET_JABATAN",
  DELETE_JABATAN: "DELETE_JABATAN",
};

export const KARYAWAN_TYPES = {
  CREATE_KARYAWAN: "CREATE_KARYAWAN",
  LOADING_KARYAWAN: "LOADING_KARYAWAN",
  GET_KARYAWANS: "GET_KARYAWANS",
  UPDATE_KARYAWAN: "UPDATE_KARYAWAN",
  GET_KARYAWAN: "GET_KARYAWAN",
  DELETE_KARYAWAN: "DELETE_KARYAWAN",
};
